version: "3.9"

services:
  vite-app:
    image: nginx:alpine
    container_name: vite_app
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # nếu có config riêng